import type { NextPage, Metadata } from "next";
import React from "react";

import { RecoilProvider, AuthProvider, HotToastProvider } from "@src/context";

import "./globals.css";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

const RootLayout: NextPage<React.PropsWithChildren> = ({ children }) => {
   return (
      <html lang="en" data-theme="mytheme">
         <body>
            <RecoilProvider>
               <AuthProvider>
                  <HotToastProvider>{children}</HotToastProvider>
               </AuthProvider>
            </RecoilProvider>
         </body>
      </html>
   );
};

export default RootLayout;
